form/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

gallery/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

homepage/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

schedule/urls.py
from django.urls import re_path
from .views import index, newschedule, addschedule, resetschedule
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^addschedule', addschedule, name='addschedule'),
    re_path(r'^new_schedule', newschedule, name='newschedule'),
    re_path(r'^resetschedule', resetschedule, name='resetschedule'),
]

story/urls.py
from django.contrib import admin
from django.urls import re_path
from django.conf.urls import include
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^homepage/', include('homepage.urls')),
    re_path(r'^gallery/', include('gallery.urls')),
    re_path(r'^form/', include('form.urls')),
    re_path(r'^schedule/', include(('schedule.urls', 'schedule'), namespace='schedule')),
    re_path(r'^$', RedirectView.as_view(url='/homepage/', permanent=True), name='index')
]

form/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models
from datetime import datetime, date


DAYS_CHOICES = [
	("Sunday", "Sunday"),
	("Monday", "Monday"),
	("Tuesday", "Tuesday"),
	("Wednesday", "Wednesday"),
	("Thursday", "Thursday"),
	("Friday", "Friday"),
	("Saturday", "Saturday"),
	]	

class Schedule(models.Model):
	title = models.CharField("Title", max_length=27)
	day = models.CharField("Day", choices=DAYS_CHOICES, max_length=9)
	date = models.DateField("Date")
	start_time = models.TimeField("Start Time")
	end_time = models.TimeField("End Time")
	place = models.CharField("Place", max_length=27) 
	category = models.CharField("Category", max_length=10)

schedule/forms.py
from .models import Schedule, DAYS_CHOICES
from django.forms import ModelForm
from django import forms
import datetime

class ScheduleForm(ModelForm):

    title = forms.CharField(max_length=27, widget=forms.TextInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': "Enter the title of the event ..."
    	}
    ))

    day = forms.ChoiceField(choices=DAYS_CHOICES, widget=forms.Select(
    	attrs={
    		'class': 'form-control',
    	}
    ))

    date = forms.DateField(widget=forms.DateInput(
    	attrs={
    		'class': 'form-control',
    		'type' : 'date',
    	}
    ))

    start_time = forms.TimeField(widget=forms.TimeInput(
    	attrs={
    		'class': 'form-control',
    		'type' : 'time',
    	}
    ))

    end_time = forms.TimeField(widget=forms.TimeInput(
    	attrs={
    		'class': 'form-control',
    		'type' : 'time',
    	}
    ))

    place = forms.CharField(max_length=27, widget=forms.TextInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': "Enter the place of the event ..."
    	}
    ))

    category = forms.CharField(max_length=27, widget=forms.TextInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': "Enter the category of the event ..."
    	}
    ))

    class Meta:
        model = Schedule
        fields = '__all__'

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        day = self.cleaned_data['day']
        try:
            date = self.cleaned_data['date']
        except :
            return start_time
       
        date_time_start = ('%s %s' % (date,start_time))
        date_time_start = datetime.datetime.strptime(date_time_start, '%Y-%m-%d %H:%M:%S')

        date_day = date_time_start.strftime("%A")
        if date_time_start < datetime.datetime.now():
            self.add_error('start_time', 'Cannot add past event')
        if day != date_day:
            self.add_error('day', "Day mismatched with date")
        if end_time < start_time:
            self.add_error('end_time', "End time should be greater than start time.")
        return start_time

form/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'form.html')

gallery/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'gallery.html')

homepage/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'homepage.html')

schedule/views.py
from .forms import ScheduleForm
from django.shortcuts import render
from .models import Schedule
from django.http import HttpResponseRedirect

response = {}

def index(request):
	schedule = Schedule.objects.all().values().order_by('date', 'start_time')
	response['schedule'] = schedule

	return render(request, 'schedule.html', response)

def newschedule(request):
    """Create a new Schedule model."""
    form = ScheduleForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
    	response['title'] = request.POST['title']
    	response['day'] = request.POST['day']
    	response['date'] = request.POST['date']
    	response['start_time'] = request.POST['start_time']
    	response['end_time'] = request.POST['end_time']
    	response['place'] = request.POST['place']
    	response['category'] = request.POST['category']
    	schedule = Schedule(title=response['title'], day=response['day'], date=response['date'], 
			start_time=response['start_time'], end_time=response['end_time'], place=response['place'],
			category=response['category'])
    	schedule.save()
    	return HttpResponseRedirect("/../schedule/")
    response['ScheduleForm'] = form
    return render(request, "addschedule.html", response)

def addschedule(request):
	response['ScheduleForm'] = ScheduleForm
	return render(request, 'addschedule.html', response)

def resetschedule(request):
    schedule = Schedule.objects.all()
    for data in schedule:
        data.delete()
    return HttpResponseRedirect('/schedule')

form/templates/form.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Form | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
	
</head>
</style>
<body>
{% block content %}
	<div class ="main main-form">
		<div class="form-container">
			<div class="form-group row">
			  	<label for="name-input" class="col-2 col-form-label">Nama</label>
			  	<div class="col-10">
			    	<input class="form-control" type="text" placeholder="Ahmad Fauzan Amirul Isnain" id="name-input" required>
			  	</div>
			</div>
			<div class="form-group row">
			  	<label for="tanggal-lahir-input" class="col-2 col-form-label">Tanggal Lahir</label>
			  	<div class="col-10">
			    	<input class="form-control" type="date" placeholder="2002-07-17" id="tanggal-lahir-input" required>
			  	</div>
			</div>
			<div class="form-group row">
			  	<label for="email-input" class="col-2 col-form-label">Email</label>
			  	<div class="col-10">
			    	<input class="form-control" type="email" placeholder="amirul.isnain@gmail.com" id="email-input" required>
			  	</div>
			</div>
			<div class="form-group row">
			  	<label for="username-input" class="col-2 col-form-label">Username</label>
			  	<div class="col-10">
			    	<input class="form-control" type="text" placeholder="amirul_isnain458" id="username-input"required>
			  	</div>
			</div>
			<div class="form-group row">
			  	<label for="password-input" class="col-2 col-form-label">Password</label>
			  	<div class="col-10">
			    	<input class="form-control" type="password" placeholder="Enter your password" id="password-input" required>
			  	</div>
			</div>
			<div class="form-group row">
			  	<label for="confirm-password" class="col-2 col-form-label">Confirm Password</label>
			  	<div class="col-10">
			    	<input class="form-control" type="password" placeholder="Confirm your password" id="confirm-password" data-match="#password-input" data-match-error="Password does not match" required>
			  	</div>
			</div>
			<div class="form-group">
	    		<button type="submit" class="btn btn-primary">Submit</button>
	  		</div>
	  	</div>
	</div>
{% endblock content %}
</body>
</html>

gallery/templates/gallery.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Gallery | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
</head>
</style>
<body>
{% block content %}
	<div class ="main">
		<div class="container">
			<div class="panel-group">
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom zero-margin-top border border-dark">
						<h1><a name="DDP0">DDP0</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark ">
						<div class="gallery">
							<img src="{% static 'img/ddp0-1.png' %}">
							<img src="{% static 'img/ddp0-2.png' %}">
							<img src="{% static 'img/ddp0-3.png' %}">
							<img src="{% static 'img/ddp0-4.png' %}">
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Padus-Wisuda">Padus Wisuda</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="gallery">
							<img src="{% static 'img/pw-1.png' %}">
							<img src="{% static 'img/pw-2.png' %}">
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Hari-Terakhir-SMA">Hari Terakhir SMA</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="gallery">
							<img src="{% static 'img/hts-1.png' %}">
							<img src="{% static 'img/hts-2.png' %}">
							<img src="{% static 'img/hts-3.png' %}">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
</body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Profile | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
</head>
</style>
<body>
{% block content %}
	<div class ="main">
		<div class="container container-homepage-1">
			<div class="panel-group">
				<div class="panel panel-default border border-dark header">
					<div class="panel-heading">
						<a name="header"><img class="img-responsive" id="header-img" src="{% static 'img/header.png' %}"></a>
						<img class="img-responsive" id="profile_photo" src="{% static 'img/profile_photo.jpg' %}">
					</div>
					<div class="panel-body">
						<div class="container">
							<div class="row header-versi-satu">
								<div class="col-8">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-4 header-margin-bottom">
									<h2>Contact</h2>
									<div class="row block">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row block">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
							<div class="row header-versi-dua">
								<div class="col-12">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-12 auto-margin">
									<div class="row block auto-margin">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row block auto-margin">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Experience">Experience</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img src="{% static 'img/compfest.png' %}">
							<div class="inline content-word">
								<p>Staff of Equipment and Security</p>
								<p>Compfest X</p>
								<p>Feb, 2018 - Present</p>
							</div>
						</div>
						<div class="row block content">
							<img src="{% static 'img/fuki.png' %}">
							<div class="inline content-word">
								<p>Staff of Muslim Development Center</p>
								<p>Forum Ukhuwah dan Kajian Islam Fasilkom UI</p>
								<p>Feb, 2018 - Present</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Education">Education</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img src="{% static 'img/UI.png' %}">
							<div class="inline content-word"/>
								<p>Universitas Indonesia</p>
								<p>Bachelor’s  degree, Computer Science</p>
								<p>2017 - Present</p>
							</div>
						</div>
						<div class="row block content">
							<img src="{% static 'img/smanda.png' %}"/>
							<div class="inline content-word">
								<p>SMA Negeri 2 Bogor</p>
								<p>2014 - 2017</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Skills">Skills</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img src="{% static 'img/java.png' %}">
							<div class="inline content-word">
								<p>Java</p>
								<p>Object Oriented Programming</p>
							</div>
						</div>
						<div class="row block content">
							<img src="{% static 'img/python.png' %}">
							<div class="inline content-word">
								<p>Python</p>
								<p>Procedural Programming</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Accomplishments">Accomplishments</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img src="{% static 'img/fastfingers.png' %}">
							<div class="inline content-word">
								<p>98 WPM English Typing Speed Test</p>
								<p>10FastFingers</p>
								<p>2018</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Interests">Interests</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img src="{% static 'img/se.png' %}">
							<div class="inline content-word">
								<p>Software Engineering</p>
								<p>Apply principles and techniques of computer science to<br/>
								software applications for computer</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container container-homepage-2">
						<div class="panel-group">
				<div class="panel panel-default border border-dark header">
					<div class="panel-heading">
						<a name="header2"><img class="img-responsive" id="header-img" src="{% static 'img/header.png' %}"></a>
						<img class="img-responsive" id="profile_photo" src="{% static 'img/profile_photo.jpg' %}">
					</div>
					<div class="panel-body">
						<div class="container">
							<div class="row header-versi-satu">
								<div class="col-8">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-4 header-margin-bottom">
									<h2>Contact</h2>
									<div class="row block">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row block">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
							<div class="row header-versi-dua">
								<div class="col-12">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-12 auto-margin">
									<div class="row block auto-margin">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row block auto-margin">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Experience2">Experience</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/compfest.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>Staff of Equipment and Security</p>
								<p>Compfest X</p>
								<p>Feb, 2018 - Present</p>
							</div>
						</div>
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/fuki.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>Staff of Muslim Development Center</p>
								<p>Forum Ukhuwah dan Kajian Islam Fasilkom UI</p>
								<p>Feb, 2018 - Present</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Education2">Education</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/UI.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word"/>
								<p>Universitas Indonesia</p>
								<p>Bachelor’s  degree, Computer Science</p>
								<p>2017 - Present</p>
							</div>
						</div>
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/smanda.png' %}"/>
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>SMA Negeri 2 Bogor</p>
								<p>2014 - 2017</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Skills2">Skills</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/java.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>Java</p>
								<p>Object Oriented Programming</p>
							</div>
						</div>
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/python.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>Python</p>
								<p>Procedural Programming</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Accomplishments2">Accomplishments</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/fastfingers.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>98 WPM English Typing Speed Test</p>
								<p>10FastFingers</p>
								<p>2018</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading panel-heading-custom border border-dark">
						<h1><a name="Interests2">Interests</a></h1>
					</div>
					<div class="panel-body panel-body-custom border border-dark">
						<div class="row block content">
							<img class="auto-margin" src="{% static 'img/se.png' %}">
						</div>
						<div class="row block content">
							<div class="inline content-word">
								<p>Software Engineering</p>
								<p>Apply principles and techniques of computer science to<br/>
								software applications for computer</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
</body>
</html>

schedule/templates/addschedule.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Schedule | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
</head>
</style>
<body>
{% block content %}
	<div class ="main main-form">
	<div class ="form-container">
    	<form method="POST" action="{% url 'schedule:newschedule' %}">
    		{% csrf_token %}
	    		{% for data in ScheduleForm %}
					<div class="form-group row">
					  	<label class="col-2 col-form-label">{{data.label}}</label>
					  	<div class="col-10">
					    	{{data}}
					    	{% if data.errors %}
					    		{{data.errors}}
					    	{% endif %}
					  	</div>
					</div>
				{% endfor %}
        	<div class="form-group">
				<button type="submit" class="save btn btn-primary">Save</button>
			</div>
   		</form>
   	</div>
	</div>
{% endblock content %}
</body>
</html>

schedule/templates/schedule.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Profile | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
</head>
</style>
<body>
{% block content %}
	<div class ="main">
		<div class="container container-homepage-1">
			<div class="panel-group">
				{% if schedule %}
					{% for data in schedule %}
						<div class="panel panel-default">
							<div class="panel-heading panel-heading-custom zero-margin-top border border-dark">
								<h1><a name="Experience">{{data.title}}</a></h1>
							</div>
							<div class="panel-body panel-body-custom border border-dark">
								<div class="row block content">
									<div class="inline content-word">
										<p>{{data.day}}, {{data.date}}</p>
										<p>{{data.start_time}} - {{data.end_time}}</p>
										<p>Event will be held at {{data.place}}</p>
										<p>Category : {{data.category}}</p>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<div class="panel panel-default">
						<div class="panel-heading panel-heading-custom zero-margin-top border border-dark">
							<h1><a name="Experience">No Event</a></h1>
						</div>
						<div class="panel-body panel-body-custom border border-dark">
							<div class="row block content">
								<div class="inline content-word">
									<p>Enjoy your free time :D</p>
								</div>
							</div>
						</div>
					</div>
				{% endif %}
				<a href="{% url 'schedule:addschedule' %}" class="btn btn-success btn-custom">Add Schedule</a>
				<a href="{% url 'schedule:resetschedule' %}" class="btn btn-danger btn-custom">Reset Schedule</a>
			</div>
		</div>
		<div class="container container-homepage-2">
			<div class="panel-group">
				{% if schedule %}
					{% for data in schedule %}
						<div class="panel panel-default">
							<div class="panel-heading panel-heading-custom border border-dark">
								<h1><a name="Experience2">{{data.title}}</a></h1>
							</div>
							<div class="panel-body panel-body-custom border border-dark">
								<div class="row block content">
									<div class="inline content-word">
										<p>{{data.day}}, {{data.date}}</p>
										<p>{{data.start_time}} - {{data.end_time}}</p>
										<p>Event will be held at {{data.place}}</p>
										<p>Category : {{data.category}}</p>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<div class="panel panel-default">
						<div class="panel-heading panel-heading-custom border border-dark">
							<h1><a name="Experience">No Event</a></h1>
						</div>
						<div class="panel-body panel-body-custom border border-dark">
							<div class="row block content">
								<div class="inline content-word">
									<p>Enjoy your free time :D</p>
								</div>
							</div>
						</div>
					</div>
				{% endif %}
				<a href="{% url 'schedule:addschedule' %}" class="btn btn-success btn-custom">Add Schedule</a>
				<a href="{% url 'schedule:resetschedule' %}" class="btn btn-danger btn-custom">Reset Schedule</a>
			</div>
		</div>
	</div>
{% endblock content %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="shortcut icon" href="{% static 'img/icon.ico' %}" />
	{% block heading %}
	{% endblock heading %}
</head>
</style>
<body>
	<nav class="navbar-nav side-navbar">
      	<li class="nav-item" id ="nav_photo">
			<a class="nav-link" href="/homepage#header" id="profile_menu"><img src="{% static 'img/profile_photo.jpg' %}"></a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/homepage#Experience">Experience</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/homepage#Education">Education</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/homepage#Skills">Skills</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/homepage#Accomplishments">Accomplishments</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/homepage#Interests">Interests</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/gallery">Gallery</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/form">Register</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/schedule">Schedule</a>
		</li>
	</nav>
	<nav class="navbar navbar-expand-sm top-navbar fixed-top">
		<ul class="navbar-nav">
	      	<li class="nav-item">
				<a class="nav-link" href="/homepage#header2">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/homepage#Experience2">Experience</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/homepage#Education2">Education</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/homepage#Skills2">Skills</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/homepage#Accomplishments2">Accomplishments</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/homepage#Interests2">Interests</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/gallery">Gallery</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/form">Register</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/schedule">Schedule</a>
			</li>
		</ul>
	</nav>
	{% block content %}
	{% endblock content %}
</body>
</html>